<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NameSarah PasaribuEmailsarahasaribu1234_b2b06c</name>
   <tag></tag>
   <elementGuidId>e1a5579b-4aaa-474e-8317-7466055e6e1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='output']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.border.col-md-12.col-sm-12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>00564aea-1ee2-41d3-bcdc-e3bcea98ae05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border col-md-12 col-sm-12</value>
      <webElementGuid>48cf42bd-d942-43a6-a617-2cc654d5f014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name:Sarah PasaribuEmail:sarahasaribu1234@gmail.comCurrent Address :Medan Permananet Address :medan</value>
      <webElementGuid>7c023baf-e0c0-4e2b-869f-1340bfb2d7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;output&quot;)/div[@class=&quot;border col-md-12 col-sm-12&quot;]</value>
      <webElementGuid>bfbb08f3-2328-42b2-9d57-fb8c422ebdc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='output']/div</value>
      <webElementGuid>c687d3e6-709d-4533-9f26-e909a2be7868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[6]/div</value>
      <webElementGuid>cbb032b1-60ee-49a9-9770-ee294c97389d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Name:Sarah PasaribuEmail:sarahasaribu1234@gmail.comCurrent Address :Medan Permananet Address :medan' or . = 'Name:Sarah PasaribuEmail:sarahasaribu1234@gmail.comCurrent Address :Medan Permananet Address :medan')]</value>
      <webElementGuid>cb593194-ce94-4b4a-9917-eef9b101dad2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
