<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Register to Book StoreFirst Name Last _8edb18</name>
   <tag></tag>
   <elementGuidId>2c9eb418-f445-4c90-8437-59d65afe8f77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#userForm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='userForm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>9f49d434-e22d-45de-9b84-fc3a4ba40cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userForm</value>
      <webElementGuid>b7613171-4de8-4397-a410-98e66b79bffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register to Book StoreFirst Name :Last Name : UserName : Password : RegisterBack to Login</value>
      <webElementGuid>109c5e93-29d8-45e6-8f7b-28742f528bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userForm&quot;)</value>
      <webElementGuid>9698a53a-0053-45d0-9863-307f93ec1039</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='userForm']</value>
      <webElementGuid>0bd33a39-29ed-4f0e-acde-73d08e61551d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div[2]/div[2]/form</value>
      <webElementGuid>794b0bd2-f29a-4823-a4bc-3e66ec13e79b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>e68380d4-6273-4165-9228-bffc6dfc22cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'userForm' and (text() = 'Register to Book StoreFirst Name :Last Name : UserName : Password : RegisterBack to Login' or . = 'Register to Book StoreFirst Name :Last Name : UserName : Password : RegisterBack to Login')]</value>
      <webElementGuid>2f445033-af18-4451-9b37-b95f13e2d985</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
