<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>83b16616-62f0-4794-bb6e-710c32e07fb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td.rc-imageselect-tile > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-44</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4659772c-de4c-4748-9750-3c5f5973b92e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>93af5e38-ddf4-46df-b1f7-fb8392d15060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5gkGrWxp6ZLTP7y_Zu5jA9EO129n203wHLEE4ZFW3EKAUpS-QEQAvudeA4ORYX17Cz4fWOZo9WPqAoZXZ66eqG4x1b7Dfas2l41PRZ7IYcL2blldvHcX54h7SNQIjc00-j783Hq7DZglQzxgt-XO0lqXlZ9fO0PKukNH_xdUP_HeEXtYwCv5y4gUerrqyNsbNyXAup5VlV7aWQdSkIisawlHagAQ&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7</value>
      <webElementGuid>df390902-9562-48b1-9b03-b22e36de9681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>3c67192c-dbcf-4823-a03e-88cba0103898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/register/Page_DEMOQA/iframe_c-yunr4ipq010t</value>
      <webElementGuid>32abbaab-da8f-43e9-9491-979a11014059</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td/div/div/img</value>
      <webElementGuid>dbb7bc6c-263b-4651-b77b-570dc6f71aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5gkGrWxp6ZLTP7y_Zu5jA9EO129n203wHLEE4ZFW3EKAUpS-QEQAvudeA4ORYX17Cz4fWOZo9WPqAoZXZ66eqG4x1b7Dfas2l41PRZ7IYcL2blldvHcX54h7SNQIjc00-j783Hq7DZglQzxgt-XO0lqXlZ9fO0PKukNH_xdUP_HeEXtYwCv5y4gUerrqyNsbNyXAup5VlV7aWQdSkIisawlHagAQ&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7')])[5]</value>
      <webElementGuid>8661a043-02b7-458f-87af-6f6f73fc365d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div/img</value>
      <webElementGuid>38c91eba-bed0-4389-a2b8-136f5ebd14c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5gkGrWxp6ZLTP7y_Zu5jA9EO129n203wHLEE4ZFW3EKAUpS-QEQAvudeA4ORYX17Cz4fWOZo9WPqAoZXZ66eqG4x1b7Dfas2l41PRZ7IYcL2blldvHcX54h7SNQIjc00-j783Hq7DZglQzxgt-XO0lqXlZ9fO0PKukNH_xdUP_HeEXtYwCv5y4gUerrqyNsbNyXAup5VlV7aWQdSkIisawlHagAQ&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7']</value>
      <webElementGuid>4054fe55-fc54-4a21-84ff-6257a89b05d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
