<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>46f82ddb-ad7f-4dd2-bfef-607301acf3e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td.rc-imageselect-tile > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>afd5413f-6742-47ed-87ee-59071e62a813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>c1dd5db6-7699-452a-9002-192c8ef356fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5aahxEkryuvTTaxFRWsTNRA843TKYNEs1PX_o90uM1qXCk3_GC3JnZ_LA7vgKn64udPCIt5OW6oKjOo3gSFYv8pw3YAN6tt-680xDZbCwl4QQXXep8QYZnk9mUc-cK1OKlbSVVaKnhzG3VOxo-7riMcWOUnV5BzAdMdsb4BwGoc_ODnVOewYHknc1HIgNeTV2yNCUN&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7</value>
      <webElementGuid>467e1867-8a45-4671-868a-816ad114175d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>38e048c2-e1cc-4b7e-97e7-c142cc0af9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/register/Page_DEMOQA/iframe_c-yunr4ipq010t</value>
      <webElementGuid>f728b1b2-ff42-4ad9-b771-c5b15fa9f4bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td/div/div/img</value>
      <webElementGuid>ac1a7757-52b9-4248-8347-ecbcfb59d7e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5aahxEkryuvTTaxFRWsTNRA843TKYNEs1PX_o90uM1qXCk3_GC3JnZ_LA7vgKn64udPCIt5OW6oKjOo3gSFYv8pw3YAN6tt-680xDZbCwl4QQXXep8QYZnk9mUc-cK1OKlbSVVaKnhzG3VOxo-7riMcWOUnV5BzAdMdsb4BwGoc_ODnVOewYHknc1HIgNeTV2yNCUN&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7')])[4]</value>
      <webElementGuid>f358cd7a-2563-4130-bb7a-cc3581ac00c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div/img</value>
      <webElementGuid>a11071fa-14bd-4692-ac6e-c11ddef8c431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5aahxEkryuvTTaxFRWsTNRA843TKYNEs1PX_o90uM1qXCk3_GC3JnZ_LA7vgKn64udPCIt5OW6oKjOo3gSFYv8pw3YAN6tt-680xDZbCwl4QQXXep8QYZnk9mUc-cK1OKlbSVVaKnhzG3VOxo-7riMcWOUnV5BzAdMdsb4BwGoc_ODnVOewYHknc1HIgNeTV2yNCUN&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7']</value>
      <webElementGuid>9e2b598e-915d-4260-baf9-bcd34780ce6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
