<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_New Window Message</name>
   <tag></tag>
   <elementGuidId>b937ab5c-c134-4554-88a5-f60bffcd999a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='messageWindowButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#messageWindowButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e8371010-6157-405e-961e-2676fc6eca2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>messageWindowButton</value>
      <webElementGuid>5f0515af-2f2d-4995-8fc3-dce56e24c7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b0bf1c77-e39c-4ff7-b26b-cef09bd08efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>cb22417e-6706-43e1-a099-965e92dca645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Window Message</value>
      <webElementGuid>8f557124-fabe-4e77-8cf7-115bb875ffdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;messageWindowButton&quot;)</value>
      <webElementGuid>64911657-26fa-4ed2-9ef2-3fb11d46ccc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='messageWindowButton']</value>
      <webElementGuid>7f82652e-3e85-4e01-9099-f31964968e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='msgWindowButtonWrapper']/button</value>
      <webElementGuid>6e880c82-9779-402f-a565-79f2e5cd6439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>f453fa9e-5978-404f-9673-993c99d81b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'messageWindowButton' and @type = 'button' and (text() = 'New Window Message' or . = 'New Window Message')]</value>
      <webElementGuid>934b5f62-fc1c-4822-ad97-8c8a51f43d6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
