<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Welcome,Login in Book StoreUserName  P_1bd0cd</name>
   <tag></tag>
   <elementGuidId>9116ef61-25c5-4782-b6d1-453df8902439</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='userForm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#userForm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>592b96de-12ea-4dce-a112-4e417009735e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userForm</value>
      <webElementGuid>008b95fc-2184-45f4-b1f7-deb74fff3b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome,Login in Book StoreUserName : Password : LoginNew User</value>
      <webElementGuid>3f94e4b7-95db-4c04-84b8-5b8696906809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userForm&quot;)</value>
      <webElementGuid>fa17e565-cf7e-428e-8680-302b9f95adce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='userForm']</value>
      <webElementGuid>48c606e1-3ea3-468c-aae5-5d0b5a65bdfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div[2]/div[2]/form</value>
      <webElementGuid>cc152dd6-63e6-4e3f-a921-cecd1ff06b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>42c88dba-2828-4ae8-b202-8da7dfbe6f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'userForm' and (text() = 'Welcome,Login in Book StoreUserName : Password : LoginNew User' or . = 'Welcome,Login in Book StoreUserName : Password : LoginNew User')]</value>
      <webElementGuid>cb956e1d-31b5-47c0-a123-502e1e5fcfdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
