<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_This is a sample page</name>
   <tag></tag>
   <elementGuidId>a0e36625-f443-4a85-a8b1-6322f8a905d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='sampleHeading']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sampleHeading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>98a73136-8ae7-4dcb-a89c-e4ae5ecd0c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sampleHeading</value>
      <webElementGuid>ca3185c8-cb08-48ee-b9fa-f77a780bc77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This is a sample page</value>
      <webElementGuid>f9a211f8-5460-4ec0-9bcb-dc08fef22ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sampleHeading&quot;)</value>
      <webElementGuid>9eae044e-1624-4c75-9bcf-11bc0cf4f94f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='sampleHeading']</value>
      <webElementGuid>1eebfc41-8bd7-4581-a118-aeabf8557c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>7246a069-2e9a-4634-9e6f-658d82cc1ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'sampleHeading' and (text() = 'This is a sample page' or . = 'This is a sample page')]</value>
      <webElementGuid>6e0fe840-95d5-4e74-9a7b-37dd8bf107d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
